namespace SmartCrawler.Urls;

public static class UrlSamples
{
    public static string[] LawFirmsInSanFrancisco = new[]
    {
        "https://dolanlawfirm.com/",
        "https://www.cartwrightlaw.com/",
        "https://www.orrick.com/Locations/Bay-Area-San-Francisco-and-Silicon-Valley",
        "https://www.leighlawgroup.com/?npcmp=dir:local:3587704:Leigh Law Group",
        "https://hallinanlawfirm.com/",
        "https://www.usimmigrationplan.com/",
        "https://sfcriminallawspecialist.com/?utm_source=gmb&utm_medium=organic&utm_campaign=website-san-francisco",
        "http://www.leivafirm.com/",
        "https://www.kpbimmigrationlawfirm.com/",
        "https://www.sflg.com/?utm_source=gmb&utm_medium=organic&utm_campaign=gmb-listing",
        "https://www.scarlettlawgroup.com/",
        "https://goodrowlaw.com/",
        "https://www.thearmstronglawfirm.com/?npcmp=dir:local:3446690:The Armstrong Law Firm",
        "http://www.northerncaliforniacriminaldefense.com/",
        "https://www.tobenerlaw.com/",
        "http://railaw.com/",
        "https://www.ottingerlaw.com/san-francisco-employment-lawyers/?utm_source=gmb&utm_medium=local&utm_campaign=sanfrancisco",
        "https://www.mofo.com/offices/san-francisco.html",
        "http://www.vlplawgroup.com/attorneys/david-goldenberg/",
        "https://www.danroselaw.com/",
        "https://dolanlawfirm.com/",
        "https://www.cartwrightlaw.com/",
        "https://www.orrick.com/Locations/Bay-Area-San-Francisco-and-Silicon-Valley",
        "https://www.leighlawgroup.com/?npcmp=dir:local:3587704:Leigh Law Group",
        "https://hallinanlawfirm.com/",
        "https://www.usimmigrationplan.com/",
        "https://sfcriminallawspecialist.com/?utm_source=gmb&utm_medium=organic&utm_campaign=website-san-francisco",
        "http://www.leivafirm.com/",
        "https://www.kpbimmigrationlawfirm.com/",
        "https://www.sflg.com/?utm_source=gmb&utm_medium=organic&utm_campaign=gmb-listing",
        "https://www.scarlettlawgroup.com/",
        "https://goodrowlaw.com/",
        "https://www.thearmstronglawfirm.com/?npcmp=dir:local:3446690:The Armstrong Law Firm",
        "http://www.northerncaliforniacriminaldefense.com/",
        "https://www.tobenerlaw.com/",
        "http://railaw.com/",
        "https://www.ottingerlaw.com/san-francisco-employment-lawyers/?utm_source=gmb&utm_medium=local&utm_campaign=sanfrancisco",
        "https://www.mofo.com/offices/san-francisco.html",
        "http://www.vlplawgroup.com/attorneys/david-goldenberg/",
        "https://www.danroselaw.com/",
        "https://dolanlawfirm.com/",
        "https://www.cartwrightlaw.com/",
        "https://www.orrick.com/Locations/Bay-Area-San-Francisco-and-Silicon-Valley",
        "https://www.leighlawgroup.com/?npcmp=dir:local:3587704:Leigh Law Group",
        "https://hallinanlawfirm.com/",
        "https://www.usimmigrationplan.com/",
        "https://sfcriminallawspecialist.com/?utm_source=gmb&utm_medium=organic&utm_campaign=website-san-francisco",
        "http://www.leivafirm.com/",
        "https://www.kpbimmigrationlawfirm.com/",
        "https://www.sflg.com/?utm_source=gmb&utm_medium=organic&utm_campaign=gmb-listing",
        "https://www.scarlettlawgroup.com/",
        "https://goodrowlaw.com/",
        "https://www.thearmstronglawfirm.com/?npcmp=dir:local:3446690:The Armstrong Law Firm",
        "http://www.northerncaliforniacriminaldefense.com/",
        "https://www.tobenerlaw.com/",
        "http://railaw.com/",
        "https://www.ottingerlaw.com/san-francisco-employment-lawyers/?utm_source=gmb&utm_medium=local&utm_campaign=sanfrancisco",
        "https://www.mofo.com/offices/san-francisco.html",
        "http://www.vlplawgroup.com/attorneys/david-goldenberg/",
        "https://www.danroselaw.com/"
    };
}